# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Mike Ulvila
email: mikeulvila@me.com
description: Full stack software developer with skills in Javascript, Angular, Node, Express, and MongoDB
url: "http://mikeulvila.com" # the base hostname & protocol for your site
twitter_username: mikeulvila
github_username:  mikeulvila

# Build settings
markdown: kramdown
permalink: pretty

# Contact Section
social:
- {icon: 'fa-github-square', link: 'https://github.com/mikeulvila'}
- {icon: 'fa-linkedin-square', link: 'http://www.linkedin.com/in/mike-ulvila-702b9488'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
